# ######################################################################################################################
# Prime Gaming Loot Discord Bot
# ######################################################################################################################

# Token
token: 0

# ######################################################################################################################
# Loot
# ######################################################################################################################

# The command to use in chat to display current prime gaming content
command_for_content: "!twitch"

# Message type
# - Choose 0 if you want all loot displayed in a single message from the bot
# - Choose 1 if you want an individual message for each loot (this might spam the chat very quickly)
message_type: 1

# List of games to display if there is loot
games_to_include:
  - Overwatch
  - World of Warcraft
  - Fall Guys